TC-62 Work Item list
marcelogaray/auto-GA-v01 pull request #12
Opened 2018-06-21 03:37 UTC by LinetTorrico

TC-62 Work Item list
1. Including work item list feature
2. Work Item List
![workitemlist](https://user-images.githubusercontent.com/29335751/41696427-193207e4-74e2-11e8-850f-2dee009f8171.PNG)

2018-06-21 23:12 UTC, marcelogaray requested changes
review observations

2018-06-21 23:12 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +
please user format code
remove blank line

2018-06-21 23:12 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +
remove multiples black lines

2018-06-21 23:12 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
>          CommonEvents.clickButton(personnelMenu);
it should be returned a page object according to purpose

2018-06-21 23:12 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/workItem/WorkItemList.java
> +public class WorkItemList extends BasePage {
this class needs a constructure

2018-06-21 23:12 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
>          Assert.assertTrue(result);
when this assertion will fail then you will need to set an error message

2018-06-21 23:12 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
> +        ssiaHome.clickOnWorkItemsMenu();
review your structure according to before observation

2018-06-21 23:12 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
> +        Assert.assertTrue(workItemList.isWorkItemListPresent(), "Fail, Work Item list is not loaded");
workitmelist should be reviewed it.

2018-06-22 00:16 UTC, LinetTorrico commented
1. please user format code remove blank line (Fixed)
2. it should be returned a page object according to purpose (Fixed)
3. this class needs a constructure (Fixed)
4. when this assertion will fail then you will need to set an error message (Fixed)
![workitemlist](https://user-images.githubusercontent.com/29335751/41751541-e2a517e4-758f-11e8-8c4a-69421e184d65.PNG)

2018-06-22 01:05 UTC, LinetTorrico commented
On and Clicking has been removed

2018-06-22 04:18 UTC, marcelogaray requested changes
review observations

2018-06-22 04:18 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
>          CommonEvents.clickButton(personnelMenu);
please rename this method clickPersonnelMenu

2018-06-22 04:18 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +    public void clickOnWorkItemsMenu() {
remove this method, it is not return an object.

2018-06-22 04:18 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +    public WorkItemList clickOnWorkItemMenu() {
please rename this method clickWorkItemMenu

2018-06-22 18:15 UTC, LinetTorrico commented
Corrections has been fixed 
![corrections 06-22-2018](https://user-images.githubusercontent.com/29335751/41792388-b8c9286a-7626-11e8-9151-5b14d4399a0d.png)

2018-06-22 18:50 UTC, marcelogaray requested changes
review observations

2018-06-22 18:50 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +
I see multiple blank lines, please fix it.

2018-06-22 18:50 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +
remove blank line

2018-06-22 18:50 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +
remove blank line

2018-06-22 18:50 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/menuheader/workItemsMenu/WorkItemsMenu.java
> +
remove blank line

2018-06-22 18:51 UTC, marcelogaray commented
Please fix conflicts and my observations
Send me a pull request once you fix it, I will close it in the meantime

2018-06-22 18:51 UTC, closed without merging