TC-17 Create role test case automation and add resource manager for SSIA
marcelogaray/auto-GA-v01 pull request #13
Opened 2018-06-21 07:02 UTC by airmiky

![imagen](https://user-images.githubusercontent.com/38679620/41702733-271e9ee0-74ff-11e8-8977-950c1e512bb4.png)

![imagen](https://user-images.githubusercontent.com/38679620/41702772-49c711ca-74ff-11e8-9d40-86c6fa32e401.png)

2018-06-22 02:18 UTC, marcelogaray requested changes
review observations

2018-06-22 02:18 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/role/RoleList.java
> +    @FindBy(xpath = "//*[@id='roleTable']/tbody/tr[last()]/td[1]")
review locator
dont use tboby
dont user * -> div , ul
//div[@id='...']/descendant::th[text()='HEADERE1']/tr[last()]/td

2018-06-22 04:41 UTC, marcelogaray requested changes
review second part of observations

2018-06-22 04:41 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/role/RoleCreate.java
> +    public void fillRole() {
rename this method to  "fillRoleUsingDataDriverTest"

2018-06-22 04:41 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/role/RoleCreate.java
> +        fillName(SSIAResourceManager.i.getKey("Role.create.name"));
use 'DataDriverTest' instead of 'SSIAResourceManager'
Example
DataDriverTest.readValues.getValue("Role.create.name"));

2018-06-22 04:41 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/utils/SSIAResourceManager.java
> +public class SSIAResourceManager {
use 'DataDriverTest' instead of 'SSIAResourceManager'

2018-06-22 04:41 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/utils/SSIAResourceManager.java
> +    public static final SSIAResourceManager i = new SSIAResourceManager();
user 'readValues' instead of 'i'

2018-06-22 04:41 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/utils/SSIAResourceManager.java
> +            return value;
it should return log events when there is  exception

2018-06-22 04:41 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
> +        roleCreate.fillRole();
it should be  'roleCreate.fillRoleUsingDataDriverTest'

2018-06-22 04:41 UTC, marcelogaray commented on src/test/resources/features/role/RoleCreate.feature
> +    And set 'role' data in create form page
Example you should use:
And fill 'Role' form using Data Driver Test on 'Role List' page

2018-06-22 04:41 UTC, marcelogaray commented on src/test/resources/features/role/RoleCreate.feature
> +    And Clicking on Personnel menu on 'Header' page
Please use the format that we mentioned on class.
Example
And click 'Persona' menu on 'Header' page

2018-06-22 18:53 UTC, marcelogaray requested changes
review before comment of it too.

2018-06-22 18:53 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
> +        roleCreate.fillRole();
please fix it.

2018-06-22 18:53 UTC, marcelogaray commented
Please fix conflicts and my observations
Send me a pull request once you fix it, I will close it in the meantime

2018-06-25 18:24 UTC, airmiky commented on src/test/resources/features/role/RoleCreate.feature
> +    And Clicking on Personnel menu on 'Header' page
Este step definition, es general para el evento 'click' en el menu 'personal' y lo esta revisando Lizeth.

2018-06-25 19:00 UTC, airmiky commented
![imagen](https://user-images.githubusercontent.com/38679620/41869793-25d93de2-7888-11e8-9a57-f1d8b19bd4f1.png)

![imagen](https://user-images.githubusercontent.com/38679620/41869814-3b300612-7888-11e8-844b-e997f722bd68.png)


Reabro el Pull Request con las observaciones y los conflictos resueltos, por favor validemelo Ing. Marcelo.

2018-06-28 20:32 UTC, neyber reviewed
Please review

2018-06-28 20:32 UTC, neyber commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
> +    @And("^click in sub menu 'Roles' of menu 'personnel'$")
Don't use "click in"

2018-06-28 20:32 UTC, neyber commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
>      @And("^click in button 'Create' into create form page$")
Don't use "click in"

2018-06-28 20:32 UTC, neyber commented on src/test/resources/features/role/RoleCreate.feature
> +    And click in sub menu 'Roles' of menu 'personnel'
Don't use "click in"

2018-06-28 20:32 UTC, neyber commented on src/test/resources/features/role/RoleList.feature
> +    And click in sub menu 'Roles' of menu 'personnel'
Don't use "click in"

2018-06-28 23:04 UTC, airmiky commented
Observaciones de neyber fixed.
![imagen](https://user-images.githubusercontent.com/38679620/42064877-01d71b96-7b06-11e8-90a4-cb96b4096b50.png)

![imagen](https://user-images.githubusercontent.com/38679620/42064896-12fae812-7b06-11e8-8a0d-46abe700ce04.png)

2018-06-28 23:13 UTC, merged