TC-44 personal protection equipment classification list - test case automation
marcelogaray/auto-GA-v01 pull request #14
Opened 2018-06-21 20:18 UTC by wcolina

Automated test case for "TC-44 personal protection equipment classification list".

2018-06-21 20:50 UTC, wcolina commented
Test case:
![image](https://user-images.githubusercontent.com/852076/41744876-211153ac-7573-11e8-9739-8a5a9b2f7384.png)

Automated test case result:
![image](https://user-images.githubusercontent.com/852076/41744893-30b16c5c-7573-11e8-8818-032179c45b55.png)

2018-06-22 00:39 UTC, marcelogaray requested changes
review observations

2018-06-22 00:39 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +    @FindBy(id = "ppeMenu")
please format your code
user abbreviations

2018-06-22 00:39 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
>      public void clickOnPersonnelMenu(){
user clickPersonnelMenu instead of clickOnPersonnelMenu, for all method in this class

2018-06-22 00:39 UTC, marcelogaray commented on src/test/resources/features/personalProtectionEquipment/PpeClassificationList.feature
> +    And Click in sub menu 'PPE Classification' of menu 'PPE'
click 'PPE Classification' menu on 'PPE' page

2018-06-22 00:39 UTC, marcelogaray commented on src/test/resources/features/personalProtectionEquipment/PpeClassificationList.feature
> +    And Clicking on PPE menu on 'Header' page
And click 'PPE' menu on 'Header' page

2018-06-22 01:23 UTC, wcolina commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +    @FindBy(id = "ppeMenu")
Done.

2018-06-22 02:13 UTC, wcolina commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +    @FindBy(id = "ppeMenu")
Fixed observations.

2018-06-22 05:04 UTC, marcelogaray requested changes
review observations

2018-06-22 05:04 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +        import org.openqa.selenium.WebElement;
you added spaces. please update this one.

2018-06-22 05:04 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/home/SSIAHome.java
> +    public EmployeeList clickOnEmployeeMenu() {
please change the name to 'clickEmployeeMenu'

2018-06-22 05:04 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ppe/PPEClassificationList.java
> +public class PPEClassificationList extends BasePage {
this page should have a constructure where it should wait for something in specia.

2018-06-22 18:53 UTC, marcelogaray commented
Please fix conflicts and my observations
Send me a pull request once you fix it, I will close it in the meantime

2018-06-22 18:53 UTC, closed without merging