Tc 32 henry bustamante 02
marcelogaray/auto-GA-v01 pull request #26
Opened 2018-06-26 02:30 UTC by henrybc08

another pull request to move on a separate call (step) save button for accident form

2018-06-29 21:27 UTC, lizeth-salazar commented on src/main/java/org/umssdiplo/automationv01/core/managepage/accident/AccidentForm.java
> +
Please remove this space

2018-06-29 21:28 UTC, lizeth-salazar commented on src/main/java/org/umssdiplo/automationv01/core/managepage/accident/AccidentForm.java
> +
Please add constructor for this class

2018-06-29 21:28 UTC, lizeth-salazar commented on src/main/java/org/umssdiplo/automationv01/core/managepage/accident/AccidentForm.java
> +
Remove this blank space

2018-06-29 21:29 UTC, lizeth-salazar commented on src/main/java/org/umssdiplo/automationv01/core/managepage/accident/AccidentForm.java
> +        CommonEvents.selectOptionFieldByValue(employeeList, "6");
Every single line should be a specific method to add values into a field

2018-06-29 21:31 UTC, lizeth-salazar commented on src/test/resources/features/accident/CreateAccident.feature
> +    #Then 'Accident list' page loads correctly
Remove this commented line

2018-06-29 21:32 UTC, lizeth-salazar commented on src/test/resources/features/accident/CreateAccident.feature
> +    And click Safety 'menu' on 'Header' page
'Safety' should be into the single quotes

2018-06-29 21:32 UTC, lizeth-salazar requested changes
Please review the comments

2018-06-30 20:35 UTC, henrybc08 commented
![captura de pantalla 2018-06-30 a las 16 30 27](https://user-images.githubusercontent.com/38562156/42128878-80a5b2ec-7c83-11e8-8abb-d3ca3da48b00.png)
![captura de pantalla 2018-06-30 a las 16 25 37](https://user-images.githubusercontent.com/38562156/42128879-80edb7fe-7c83-11e8-90bd-f00fac9ba23a.png)
All observations were corrected

2018-07-01 03:20 UTC, merged