930 tc61 linet torrico 05
marcelogaray/auto-GA-v01 pull request #37
Opened 2018-06-26 23:47 UTC by LinetTorrico

Delete Work Item
![image](https://user-images.githubusercontent.com/29335751/41945168-ad326d76-7979-11e8-9240-09005387bd54.png)
![image](https://user-images.githubusercontent.com/29335751/41945180-bf803936-7979-11e8-825a-01fb341cb30c.png)

2018-06-27 19:28 UTC, LinetTorrico commented
Work Item update feature
![image](https://user-images.githubusercontent.com/29335751/41995142-b7ff1984-7a1e-11e8-9467-fd4684e99a71.png)

2018-06-29 05:35 UTC, LinetTorrico commented
Update work item test case have included

![image](https://user-images.githubusercontent.com/29335751/42074934-95b44f88-7b3c-11e8-8201-e3e290f030df.png)

![image](https://user-images.githubusercontent.com/29335751/42074957-a9b71b3c-7b3c-11e8-9bfb-692601603cdf.png)

2018-06-29 15:11 UTC, henrybc08 requested changes

2018-06-29 15:11 UTC, henrybc08 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/workItem/WorkItemCreate.java
> +    @FindBy(id = "saCategoryListFieldId")
saCategoryListFieldId --> este nombre corresnponde a SACategory de (Sickness Accident Category), talves seria ponerle otro id relacionado a *WorkItem*

2018-06-29 15:11 UTC, henrybc08 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/workItem/WorkItemCreate.java
> +    public void fillWorkItemUsingDataDriverTest() {
aqui talves aplicar la correccion del request 31 cobre nombres mas cortos y significatios, y agregar una descripcion en la cabecera de la clase

2018-06-29 15:11 UTC, henrybc08 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/workItem/WorkItemDelete.java
> +    public WorkItemList clickAcceptButton() {
este sleep no se si lo mantendriamos, porque recuerdo que el docente decia que podiamos sobre escribir el waitImplicit o algo parecido, 
WebElement myDynamicElement = (new WebDriverWait(driver, 10))
  .until(ExpectedConditions.presenceOfElementLocated(By.id("myDynamicElement")));
si toma mucho tiempo seria omitir esta observacion

2018-07-02 16:57 UTC, LinetTorrico commented on src/main/java/org/umssdiplo/automationv01/core/managepage/workItem/WorkItemCreate.java
> +    public void fillWorkItemUsingDataDriverTest() {
fixed

2018-07-02 16:58 UTC, LinetTorrico commented on src/main/java/org/umssdiplo/automationv01/core/managepage/workItem/WorkItemDelete.java
> +    public WorkItemList clickAcceptButton() {
fixed

2018-07-02 16:58 UTC, LinetTorrico commented
![image](https://user-images.githubusercontent.com/29335751/42176641-a1aa5504-7df7-11e8-99a5-009389d07c79.png)

2018-07-02 20:19 UTC, merged