TC 33 and 34 are committed
marcelogaray/auto-GA-v01 pull request #40
Opened 2018-07-01 02:57 UTC by henrybc08

![imagen](https://user-images.githubusercontent.com/38562156/42130648-e17b56c8-7cb8-11e8-8ffa-d7f70bc92dea.png)

Pull request for TC 33 and 34

2018-07-01 03:24 UTC, lizeth-salazar commented on src/main/java/org/umssdiplo/automationv01/core/managepage/accident/UpdateAccidentForm.java
> +
Remove this blank space please

2018-07-01 03:27 UTC, lizeth-salazar commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/ssia/SSIAStepDefinitions.java
Please remove blank space

2018-07-01 03:28 UTC, lizeth-salazar requested changes
Please remove blank spaces

2018-07-02 15:07 UTC, henrybc08 commented
![captura de pantalla 2018-07-02 a las 11 04 14](https://user-images.githubusercontent.com/38562156/42171725-0ec5a202-7de8-11e8-9959-28a9546314b9.png)

summary: Observations were corrected and conflicts were solved and tested

2018-07-02 15:09 UTC, merged